import LineGradient from "../components/LineGradient";
import { motion } from "framer-motion";

import { SiGoogleearthengine, SiTailwindcss } from "react-icons/si";
import { IoLogoJavascript } from "react-icons/io5";
import { FaReact } from "react-icons/fa";

const container = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.2,
    },
  },
};

const projectVariant = {
  hidden: { opacity: 0, scale: 0.8 },
  visible: { opacity: 1, scale: 1 },
};

const Project = ({ title, subtitle }) => {
    const overlayStyles = `absolute h-full w-full opacity-0 hover:opacity-80 transition duration-500
      bg-dark-blue z-30 flex flex-col justify-center items-center text-center p-16 text-white font-semibold`;
    const projectTitle = title.split(" ").join("-").toLowerCase();
  
    return (
      <motion.div variants={projectVariant} className="relative">
        <div className={overlayStyles}>
          <p className="text-2xl font-helvetica">{title}</p>
          <p className="mt-7">{subtitle}</p>
          {title === "EcoForecast" && (
            <div className="mt-2 flex">
              <SiGoogleearthengine className="text-xl m-2" size={32}/>
              <IoLogoJavascript className="text-xl m-2" size={32}/>
            </div>
          )}
          {title === "Personal Portfolio" && (
            <div className="mt-2 flex">
              <FaReact className="text-xl m-2" size={32}/>
              <SiTailwindcss className="text-xl m-2" size={32}/>
            </div>
          )}
        </div>
        <img src={`../assets/${projectTitle}.png`} alt={projectTitle} />
      </motion.div>
    );
  };
  
const Projects = () => {
  return (
    <section id="projects" className="pt-48 pb-48">
      {/* HEADINGS */}
      <motion.div
        className="md:w-2/5 mx-auto text-center"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.5 }}
        transition={{ duration: 0.5 }}
        variants={{
          hidden: { opacity: 0, y: -50 },
          visible: { opacity: 1, y: 0 },
        }}
      >
        <div>
          <p className="font-helvetica font-semibold text-4xl">
            Projects
          </p>
          <div className="flex justify-center mt-5">
            <LineGradient width="w-2/3" />
          </div>
        </div>
      </motion.div>

      {/* PROJECTS */}
      <div className="flex justify-center">
        <motion.div
          className="sm:grid sm:grid-cols-3"
          variants={container}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
        >
          <Project title="EcoForecast" subtitle="An app for farmers, ranchers, and land managers to visualize and analyzing future climate and plant ecosystem data. Simulation data generated by STEPWAT2. Made using Google Earth Engine JavaScript API with the Yale School of the Environment."/>
          <Project title="Personal Portfolio" subtitle="My personal portfolio website. Made using React.js and Tailwind CSS."/>
          <Project title="Project 3" />
        </motion.div>
      </div>
    </section>
  );
};

export default Projects;